abi: "Contract ABI"
address: "Your Contract Address"
function_name: "Function to call"
interval: 10 # minutes
rpc: "RPC for the chain your contract is on"
status: "A string"
token: "Discord Bot Token"